version: "3.1"
services:
  scheduler:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    container_name: mlflow
    command: >
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri sqlite:///mlflow/mlflow.db
        --default-artifact-root /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow
    restart: unless-stopped
    networks:
      - default
      - airflow

volumes:
  mlflow-data:


networks:
  airflow:
    name: airflow_918bcf_airflow
    external: true
